# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ App ]
    filters:
        cssrewrite: ~

        less:
            node: %node_bin%
            node_paths: [%kernel.root_dir%/../node_modules]
            apply_to: "\.less$"

        uglifyjs2:
            bin: %kernel.root_dir%/../node_modules/.bin/uglifyjs

        uglifycss:
            bin: %kernel.root_dir%/../node_modules/.bin/uglifycss
