imports:
    - { resource: services/global.yml }
    - { resource: services/form.yml }
    - { resource: services/user.yml }
    - { resource: services/page.yml }
    - { resource: services/search.yml }
